Add fix_permissions script to all workspaces, add postinstall to jupyter and zsh to bash

diff --git a/src/ubuntu/install/bin/sync_focal b/src/ubuntu/install/bin/sync_focal
--- a/src/ubuntu/install/bin/sync_focal
+++ b/src/ubuntu/install/bin/sync_focal
@@ -10,14 +10,20 @@ cd ${SCRIPT_PATH}/..
 # Focal based except focal
 # for work in asciiville-deluxe exodus neovim-deluxe musicplayerplus osint spiderfoot
 # ALL except focal
-for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus jammy lmstudio musicplayerplus navidrome neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
+for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus focal jammy lmstudio musicplayerplus navidrome neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
 do
-  [ -d $work/kasm-user/.local/share/icons/hicolor/256x256/apps ] || {
-    echo "Missing kasm-user/.local/share/icons/hicolor/256x256/apps in $work"
+  [ -d $work/kasm-user/bin ] || {
+    echo "$work/kasm-user/bin does not exist"
     continue
   }
-  cp focal/kasm-user/.local/share/icons/hicolor/256x256/apps/help.png \
-     $work/kasm-user/.local/share/icons/hicolor/256x256/apps
+  cp /tmp/p $work/kasm-user/bin/fix_permissions
+  chmod 755 $work/kasm-user/bin/fix_permissions
+# [ -d $work/kasm-user/.local/share/icons/hicolor/256x256/apps ] || {
+#   echo "Missing kasm-user/.local/share/icons/hicolor/256x256/apps in $work"
+#   continue
+# }
+# cp focal/kasm-user/.local/share/icons/hicolor/256x256/apps/help.png \
+#    $work/kasm-user/.local/share/icons/hicolor/256x256/apps
 # vi ${work}/kasm-user/.config/kitty/sessions/startup
 #   cp focal/kasm-user/.config/kitty/sessions/btop \
 #      $work/kasm-user/.config/kitty/sessions/btop
diff --git a/src/ubuntu/install/bin/sync_jammy b/src/ubuntu/install/bin/sync_jammy
--- a/src/ubuntu/install/bin/sync_jammy
+++ b/src/ubuntu/install/bin/sync_jammy
@@ -12,8 +12,14 @@ cd ${SCRIPT_PATH}/..
 # Some
 # for work in focal navidrome osint spiderfoot
 # ALL except jammy
-for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus focal lmstudio musicplayerplus navidrome neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
+for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus focal jammy lmstudio musicplayerplus navidrome neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
 do
+  [ -d $work/kasm-user/bin ] || {
+    echo "$work/kasm-user/bin does not exist"
+    continue
+  }
+  cp /tmp/p $work/kasm-user/bin/fix_permissions
+  chmod 755 $work/kasm-user/bin/fix_permissions
 # [ -d $work/kasm-user/.config/neofetch ] || {
 #   cp -a jammy/kasm-user/.config/neofetch $work/kasm-user/.config/neofetch
 # }
@@ -54,12 +60,12 @@ do
 #    $work/kasm-user/Desktop/obsidian.desktop
 # cp jammy/kasm-user/.local/share/doc/*.md \
 #    $work/kasm-user/.local/share/doc
-  [ -f $work/kasm-user/.config/ranger/rifle.conf ] || {
-     echo "Missing rifle.conf in $work"
-     continue
-  }
-  cp jammy/kasm-user/.config/ranger/rifle.conf \
-     $work/kasm-user/.config/ranger/rifle.conf
+# [ -f $work/kasm-user/.config/ranger/rifle.conf ] || {
+#    echo "Missing rifle.conf in $work"
+#    continue
+# }
+# cp jammy/kasm-user/.config/ranger/rifle.conf \
+#    $work/kasm-user/.config/ranger/rifle.conf
 # [ -f $work/kasm-user/.config/ranger/rc.conf ] || {
 #    echo "Missing rc.conf in $work"
 #    continue
