Add neofetch config to all workspaces, use neofetch in Kitty startup

diff --git a/src/ubuntu/install/bin/sync_focal b/src/ubuntu/install/bin/sync_focal
--- a/src/ubuntu/install/bin/sync_focal
+++ b/src/ubuntu/install/bin/sync_focal
@@ -7,16 +7,18 @@ SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
 SCRIPT_PATH="$(realpath $SCRIPT_PATH)"
 cd ${SCRIPT_PATH}/..
 
-# ALL except focal
-# for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus jammy lmstudio musicplayerplus neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
 # Focal based except focal
-for work in asciiville-deluxe exodus neovim-deluxe musicplayerplus osint spiderfoot
+# for work in asciiville-deluxe exodus neovim-deluxe musicplayerplus osint spiderfoot
+# ALL except focal
+for work in appimage asciigames asciiville-deluxe asciiville deluxe exodus jammy lmstudio musicplayerplus navidrome neovim-deluxe neovim-jammy neovim osint rclone spiderfoot wing wing-neovim
 do
-  [ -d $work/kasm-user/.config/kitty/sessions ] || {
-    echo "Missing .config/kitty/sessions in $work"
+  [ -d $work/kasm-user/.local/share/icons/hicolor/256x256/apps ] || {
+    echo "Missing kasm-user/.local/share/icons/hicolor/256x256/apps in $work"
     continue
   }
-  vi ${work}/kasm-user/.config/kitty/sessions/startup
+  cp focal/kasm-user/.local/share/icons/hicolor/256x256/apps/help.png \
+     $work/kasm-user/.local/share/icons/hicolor/256x256/apps
+# vi ${work}/kasm-user/.config/kitty/sessions/startup
 #   cp focal/kasm-user/.config/kitty/sessions/btop \
 #      $work/kasm-user/.config/kitty/sessions/btop
 #   [ -d $work/kasm-user/.config/kitty/sessions ] || {
